### ISSUE TITLE
yarn-cluster mode actually taking a singl node and core

### ISSUE THREAD

**Issue by Nav15** [citiususc/SparkBWA#13]
Hi,
I am using below command to run the  application on yarn-cluster mode:
$SPARK_HOME/bin/spark-submit --class SparkBWA --master yarn-cluster --driver-memory 8G --executor-memory 6G --executor-cores 6 --verbose --num-executors 6 SparkBWA.jar -algorithm mem -reads paired -index /Data/HumanBase/HG -partitions 16 /user/hadoop/ERR000030_HG1.fastq /user/hadoop/ERR000030_HG2.fastq /user/hadoop/op_hg_cluster_mem
As  per the parameter passed the schedular should utilize the different nodes and cores available in the clutser.
 But as shown in the attached cluster information on UI
![cluster_details](https://cloud.githubusercontent.com/assets/11848244/16406530/6dac37bc-3d2c-11e6-957c-85e37d221ea8.png)
 its taking  taking single node and 1 core only. As my data size  this time is approx 5GB(READ and Index ) hence  on terminal displaying logs as:

16/06/28 12:30:07 INFO yarn.Client: Application report for application_1467096309474_0001 (state: RUNNING)
16/06/28 12:30:08 INFO yarn.Client: Application report for application_1467096309474_0001 (state: RUNNING)
16/06/28 12:30:09 INFO yarn.Client: Application report for application_1467096309474_0001 (state: RUNNING)
16/06/28 12:30:10 INFO yarn.Client: Application report for application_1467096309474_0001 (state: RUNNING),

Some kind of  Non-ending loop.

**Comment by jmabuin** [comment]
That means that your application is running. In yarn-cluster mode you don't get to see the output in your screen. The best way to see if it is actually working is going to one of the computing node and see if the output .sam files are growing in size.

**Comment by Nav15** [comment]
@jmabuin, My concern is why its not taking  the cores  which we are giving during command line. Why it taking a single node and single core.?Please refer the command and the screen shot.
And secondly,no .sam file getting generated at  hadoop_temp_dir  path. In Running  mode for  more than 1 hr,

**Comment by jmabuin** [comment]
I don't know, that is a Spark parameter, not a SparkBWA parameter.

Please, check if it is a Spark configuration issue before sending an issue here.

**Comment by Nav15** [comment]
As per your suggestion, In temp directory  .sam file getting generated and size also increasing , but once  size reaching close t0 280 MB  files dis-appeared and new sam  file generated with incremental name,as  highlighted below. Is this expected behaviour? and program goes in running.. generating .sam file till its size grows to 280MB than  all files in  that directory got deleted automatically and than new .sam file generated ....
Would  you advise as this is  Spark configuration issue or SparkBWA?

119M Jun 28 14:53 application_1467105664702_0001-RDD1_1
 119M Jun 28 14:53 application_1467105664702_0001-RDD1_2
**78M Jun 28 14:56 SparkBWA_ERR000030_HG1.fastq-0-NoSort-application_1467105664702_0001-1.sam**

-rw-rw-r-- 1 hadoop hadoop 119M Jun 28 15:03 application_1467105664702_0001-RDD2_1
-rw-rw-r-- 1 hadoop hadoop 119M Jun 28 15:03 application_1467105664702_0001-RDD2_2
**-rw-rw-r-- 1 hadoop hadoop   0M Jun 28 15:03 SparkBWA_ERR000030_HG1.fastq-0-NoSort-application_1467105664702_0001-2.sam**

-rw-rw-r-- 1 hadoop hadoop 118M Jun 28 15:13 application_1467105664702_0001-RDD4_1
-rw-rw-r-- 1 hadoop hadoop 118M Jun 28 15:13 application_1467105664702_0001-RDD4_2
**-rw-rw-r-- 1 hadoop hadoop   0M Jun 28 15:13 SparkBWA_ERR000030_HG1.fastq-0-NoSort-application_1467105664702_0001-4.sam**

**Comment by jmabuin** [comment]
Either your executors are failing because of lack of memory or disk space, or the final results are stored in HDFS and deleted from local disk.

In any case, it does not seems to be a SparkBWA problem, I repeat.
