### ISSUE TITLE
Need advise run  to SparkBWA  with Big data set of HG

### ISSUE THREAD

**Issue by Nav15** [citiususc/SparkBWA#15]
To run this  SparkBWA application with some 10K records   each in two paried files , I am faciing below issue but it ran sucessfully with 100 records each file.  Though its  not purely not SparkBWA issue,but if you can highlight  some configuration setting that will help to run this. I  have enough memory to run 300MB files.
16/06/30 12:00:40 INFO spark.MapOutputTrackerWorker: Got the output locations
16/06/30 12:00:40 INFO storage.ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 1 blocks
16/06/30 12:00:40 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 1 ms
16/06/30 12:00:40 INFO storage.MemoryStore: Block rdd_9_2 stored as values in memory (estimated size 16.0 B, free 12.2 KB)
16/06/30 12:00:40 INFO BwaInterpreter: JMAbuin:: Writing file: /home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_1
16/06/30 12:00:40 INFO BwaInterpreter: JMAbuin:: Writing file: /home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_2
[Java_BwaJni_bwa_1jni] Arg 0 'bwa'
[Java_BwaJni_bwa_1jni] Algorithm found 1 'mem'
[Java_BwaJni_bwa_1jni] Arg 1 'mem'
[Java_BwaJni_bwa_1jni] Filename parameter -f found 2 '-f'
[Java_BwaJni_bwa_1jni] Arg 2 '-f'
[Java_BwaJni_bwa_1jni] Filename found 3 '/home/hadoop/hadoop_tempdir/SparkBWA_1_130711_FLOWCEL_10Kreads_1.fastq-32-NoSort-application_1467200285413_0004-2.sam'
[Java_BwaJni_bwa_1jni] Arg 3 '/home/hadoop/hadoop_tempdir/SparkBWA_1_130711_FLOWCEL_10Kreads_1.fastq-32-NoSort-application_1467200285413_0004-2.sam'
[Java_BwaJni_bwa_1jni] Arg 4 '/Data/HumanBase/HG'
[Java_BwaJni_bwa_1jni] Arg 5 '/home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_1'
[Java_BwaJni_bwa_1jni] Arg 6 '/home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_2'
[Java_BwaJni_bwa_1jni] option[0]: bwa.
[Java_BwaJni_bwa_1jni] option[1]: mem.
[Java_BwaJni_bwa_1jni] option[2]: /Data/HumanBase/HG.
[Java_BwaJni_bwa_1jni] option[3]: /home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_1.
[Java_BwaJni_bwa_1jni] option[4]: /home/hadoop/hadoop_tempdir/application_1467200285413_0004-RDD2_2.
[M::bwa_idx_load_from_disk] read 0 ALT contigs
**[gzclose] buffer error**

16/06/30 11:59:51 INFO cluster.YarnClientSchedulerBackend: Disabling executor 1.
16/06/30 11:59:51 INFO scheduler.DAGScheduler: Executor lost: 1 (epoch 3)
16/06/30 11:59:51 INFO storage.BlockManagerMasterEndpoint: Trying to remove executor 1 from BlockManagerMaster.
16/06/30 11:59:51 INFO storage.BlockManagerMasterEndpoint: Removing block manager BlockManagerId(1, client19.example.com, 54545)
16/06/30 11:59:51 INFO storage.BlockManagerMaster: Removed 1 successfully in removeExecutor
16/06/30 11:59:51 INFO scheduler.ShuffleMapStage: ShuffleMapStage 2 is now unavailable on executor 1 (0/1, false)
16/06/30 11:59:51 INFO scheduler.ShuffleMapStage: ShuffleMapStage 0 is now unavailable on executor 1 (0/1, false)
16/06/30 11:59:51 INFO scheduler.ShuffleMapStage: ShuffleMapStage 1 is now unavailable on executor 1 (0/1, false)
16/06/30 11:59:51 INFO cluster.YarnClientSchedulerBackend: Disabling executor 6.
16/06/30 11:59:51 INFO scheduler.DAGScheduler: Executor lost: 6 (epoch 6)
16/06/30 11:59:51 INFO storage.BlockManagerMasterEndpoint: Trying to remove executor 6 from BlockManagerMaster.
16/06/30 11:59:51 INFO storage.BlockManagerMasterEndpoint: Removing block manager BlockManagerId(6, client17.example.com, 36481)
16/06/30 11:59:51 INFO storage.BlockManagerMaster: Removed 6 successfully in removeExecutor
16/06/30 11:59:52 INFO cluster.YarnClientSchedulerBackend: Disabling executor 2.
16/06/30 11:59:52 INFO scheduler.DAGScheduler: Executor lost: 2 (epoch 9)
16/06/30 11:59:52 INFO storage.BlockManagerMasterEndpoint: Trying to remove executor 2 from BlockManagerMaster.
16/06/30 11:59:52 INFO storage.BlockManagerMasterEndpoint: Removing block manager BlockManagerId(2, client16.example.com, 59865)
16/06/30 11:59:52 INFO storage.BlockManagerMaster: Removed 2 successfully in removeExecutor
1**6/06/30 11:59:52 ERROR cluster.YarnScheduler: Lost executor 6 on client17.example.com: Container marked as failed: container_1467200285413_0004_01_000007 on host: client17.example.com. Exit status: 1. Diagnostics: Exception from container-launch.
Container id: container_1467200285413_0004_01_000007
Exit code: 1**
Stack trace: ExitCodeException exitCode=1: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
    at org.apache.hadoop.util.Shell.run(Shell.java:455)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
    at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 1

**Comment by jmabuin** [comment]
Check your version of zlib 

http://www.nature.com/nprot/journal/v9/n5/fig_tab/nprot.2014.063_T1.html
