### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by mgijsbertihodenpijl** [citiususc/SparkBWA#25]
See https://github.schubergphilis.com/mgijsbertihodenpijl/SparkBWA-docker
In progress
Still need to setup the hadoop/spark and automatic test from the README.

If you want I can make a pr whne it is finished.

**Comment by jmabuin** [comment]
Sorry it took me too much in answer.

I took a look at your repository https://github.com/mgijsbertihodenpijl/SparkBWA and I could not find anything about this docker setup. The URL you are posting doesn't work for me.

Where should I look into?
