### ISSUE TITLE
-bwaArgs option seems not working

### ISSUE THREAD

**Issue by jmoa** [citiususc/SparkBWA#27]
Hi

I have successfully ran sparkBWA using command below.

`spark-submit` --class SparkBWA --master yarn --driver-memory 1500m --executor-memory 1500m --executor-cores 1 --archives bwa.zip --verbose --num-executors 6 SparkBWA.jar -algorithm mem -reads paired -index ~/nfs_server/halvade_refs/ucsc.hg19.fasta -partitions 32 spark/NA12750/ERR000589_1.fastq spark/NA12750/ERR000589_2.fastq `spark/NA12750_adam/output`

But i wanted to add read group so i tried by giving -bwaArgs "-R "@RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589""

However, the output didn't contain the read groups.

I've tried with '-R "@RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589"'
                      "-R '@RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589'"
                      "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589"
but non of them worked.

Does sparkBWA support all the arguments in bwa?

Thanks!

**Comment by jmabuin** [comment]
I have just checked with SparkBWA 0.2 version and the command below and it worked. Please check if it works for you with this new version.

`spark-submit --class com.github.sparkbwa.SparkBWA --master yarn-cluster --driver-memory 1500m --executor-memory 7500m --executor-cores 1 --verbose --num-executors 32 sparkbwa-0.2.jar -algorithm mem -reads paired -bwaArgs "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" -index /mnt/gluster/drv0/home/usc/ec/jam/Genomica/Data/BaseHumano/hg38 -partitions 32 ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589`
