### ISSUE TITLE
about processing SparkBWA warning 

### ISSUE THREAD

**Issue by light940929** [citiususc/SparkBWA#32]
Hi~ I process the example for SparkBWA. There are some WARNING on the message and  then didn't find any log4j.xml on SparkBWA. I just guess maybe these warning I couldn't get results. Do you have any ideas?  

For example:
spark-submit --class com.github.sparkbwa.SparkBWA --master local[2] --driver-memory 1500m --executor-memory 10g --executor-cores 1 --verbose --num-executors 32  SparkBWA-0.2.jar -m -r -p --index hg38/hg38.fasta -p 32 -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589

log4j:WARN No appenders could be found for logger (com.github.sparkbwa.BwaOptions).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Many Thanks, Hannah Lin

**Comment by jmabuin** [comment]
Hi Hannah,

that warning is not important when talking about getting results. By looking at your command I can see that you want to run SparkBWA in local mode. 

We didn't test SparkBWA in this mode, however, I can see that you are requesting 2 CPUs, after that, 32 executors and 10 GB per executor, does your machine has this amount of memory?

Also, are you able to get more information (logs, output, ...) about your application?

**Comment by light940929** [comment]
Hi~ José,
I run SparkBWA on a local machine(40 cores, 250 GB). I try to use command line such as 
spark-submit --class com.github.sparkbwa.SparkBWA --master yarn --driver-memory 1500m --executor-memory 10g --executor-cores 1 --verbose --num-executors 5  SparkBWA-0.2.jar -m -r -p --index hg38/hg38.fasta -p 5 -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589

I already upload the fastq files and reference(it's already index) on hdfs.  I just guess maybe my deployMode need to be inserted some information. Do you have any ideas?

These are some information when I run SparkBWA-> 
Using properties file: null
Parsed arguments:
  master                  yarn
  deployMode              null
  executorMemory          10g
  executorCores           1
  totalExecutorCores      null
  propertiesFile          null
  driverMemory            1500m
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  null
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            5
  files                   null
  pyFiles                 null
  archives                null
  mainClass               com.github.sparkbwa.SparkBWA
  primaryResource         file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar
  name                    com.github.sparkbwa.SparkBWA
  childArgs               [-m -r -p --index hg38/hg38.fasta -p 5 -w -R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589 ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589]
  jars                    null
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file null:
  spark.driver.memory -> 1500m

Main class:
com.github.sparkbwa.SparkBWA
Arguments:
-m
-r
-p
--index
hg38/hg38.fasta
-p
5
-w
-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589
ERR000589_1.filt.fastq
ERR000589_2.filt.fastq
Output_ERR000589
System properties:
spark.executor.memory -> 10g
spark.executor.instances -> 5
spark.driver.memory -> 1500m
SPARK_SUBMIT -> true
spark.app.name -> com.github.sparkbwa.SparkBWA
spark.jars -> file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar
spark.submit.deployMode -> client
spark.master -> yarn
spark.executor.cores -> 1
Classpath elements:
file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar

log4j:WARN No appenders could be found for logger (com.github.sparkbwa.BwaOptions).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Many Thanks, Hannah Lin

**Comment by jmabuin** [comment]
The index doesn't have to be in HDFS, it has to be in your local file system

**Comment by light940929** [comment]
Hi~ I change to local file system --index ~/SparkBWA_Demo/data/ref . It's still same issue. Do you have any ideas?

Details:
spark-submit --class com.github.sparkbwa.SparkBWA --master yarn --driver-memory 1500m --executor-memory 10g --executor-cores 1 --verbose --num-executors 5  SparkBWA-0.2.jar -m -r -p --index ~/SparkBWA_Demo/data/ref -p 5 -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589

Using properties file: null
Parsed arguments:
  master                  yarn
  deployMode              null
  executorMemory          10g
  executorCores           1
  totalExecutorCores      null
  propertiesFile          null
  driverMemory            1500m
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  null
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            5
  files                   null
  pyFiles                 null
  archives                null
  mainClass               com.github.sparkbwa.SparkBWA
  primaryResource         file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar
  name                    com.github.sparkbwa.SparkBWA
  childArgs               [-m -r -p --index /home/hanjl/SparkBWA_Demo/data/ref -p 5 -w -R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589 ERR000589_1.filt.fastq ERR000589_2.filt.fastq Output_ERR000589]
  jars                    null
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file null:
  spark.driver.memory -> 1500m

Main class:
com.github.sparkbwa.SparkBWA
Arguments:
-m
-r
-p
--index
/home/hanjl/SparkBWA_Demo/data/ref
-p
5
-w
-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589
ERR000589_1.filt.fastq
ERR000589_2.filt.fastq
Output_ERR000589
System properties:
spark.executor.memory -> 10g
spark.executor.instances -> 5
spark.driver.memory -> 1500m
SPARK_SUBMIT -> true
spark.app.name -> com.github.sparkbwa.SparkBWA
spark.jars -> file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar
spark.submit.deployMode -> client
spark.master -> yarn
spark.executor.cores -> 1
Classpath elements:
file:/home/hanjl/SparkBWA_Demo/spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar

log4j:WARN No appenders could be found for logger (com.github.sparkbwa.BwaOptions).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Many Thanks, Hannah Lin

**Comment by jmabuin** [comment]
i need more info. Please check your yarn logs with 

`yarn logs -applicationId <your_application_id>`

**Comment by light940929** [comment]
Hi~ I check my log and then reset my data path 
 "spark-submit --class com.github.sparkbwa.SparkBWA --master yarn  --driver-memory 1500m --executor-memory 10g --executor-cores 1 --verbose --num-executors 5   spark-2.0.1-bin-hadoop2.7/examples/jars/SparkBWA-0.2.jar  -m -r -p  --index ~/SparkBWA_Demo/data/ref -p 5 -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" hdfs:///user/h/ERR000589_1.filt.fastq  hdfs:///user/h/ERR000589_2.filt.fastq  hdfs:///user/h/Output_ERR000589"

It shows No input & output been found.  I already check my hdfs the inputs data already on there. Do you have any ideas?

ERROR BwaOptions: [com.github.sparkbwa.BwaOptions] No input and output has been found. Aborting.
ERROR BwaOptions: [com.github.sparkbwa.BwaOptions] Other args:: 5
ERROR BwaOptions: [com.github.sparkbwa.BwaOptions] Other args:: hdfs:///user/h/ERR000589_1.filt.fastq
ERROR BwaOptions: [com.github.sparkbwa.BwaOptions] Other args:: hdfs:///user/h/ERR000589_2.filt.fastq
ERROR BwaOptions: [com.github.sparkbwa.BwaOptions] Other args:: hdfs:///user/h/Output_ERR000589

$ hdfs  dfs -ls
-rw-r--r--   1 h supergroup  ERR000589_1.filt.fastq
-rw-r--r--   1 h supergroup  ERR000589_2.filt.fastq


Many Thanks, Hannah Lin

**Comment by jmabuin** [comment]
I think that the problem here is that the new argument for the number of partitions is `-n 5`, as `-p` is for paired reads.

If you check your command, you put the parameter `-p` twice, one for paired reads and other for number of partitions. Change `-p` 5 by `-n 5` and it should work.

This is also wrong in the README example, I am going to change it.
