### ISSUE TITLE
Problem in running MEM with Sparkbwa

### ISSUE THREAD

**Issue by neozhang307** [citiususc/SparkBWA#4]
This project is amazing, I think it will help a lot of people.
But, I stuck when I try to run the program.
I need to use MEM in my work, so I try to run that mem algorithm. Everything all went right before I got following message:
16/06/16 17:27:13 ERROR BwaInterpreter: java.io.FileNotFoundException: File file:/usr/local/hadoop/tmp/SparkBWA_ERR000589_1.filt.fastq-1-NoSort-local-1466068623812-0.sam does not exist
before that I think the program had already successfully finish all the BWA computing task. But it seems that the program did not generate any output.
I know that in MEM I should use an output redirection to get the result, which is different from ALN. Should there be anything wrong with that? And are there anything I can do to fix it?

**Comment by jmabuin** [comment]
Hi @neozhang307 , thank you :)

please,can you give me more information? Have you launched SparkBWA from the spark-shell or using spark-submit? are you using the reducer phase?

**Comment by neozhang307** [comment]
![screen shot 2016-06-16 at 6 52 40 pm](https://cloud.githubusercontent.com/assets/12794740/16114385/8a39d912-33f3-11e6-879f-f14d238712f8.png)
**Well, I have launched the SparkBWA successfully, and I used spark-submit,. Here is the command I used:**
spark-submit --class SparkBWA --master local[16] --driver-memory 20G --executor-memory 20G --executor-cores 16 --archives ./bwa.zip --verbose --num-executors 1  SparkBWA.jar  -algorithm mem -reads paired -partitions 1 -index /SHARE/zlq_workstation/bwa_test/hg19/gcat_01/hg19bwaidx -threads 16 /user/zlq/input/ERR000589_1.filt.fastq /user/zlq/input/ERR000589_2.filt.fastq /user/zlq/ERR00589_out
**I have seem the BWA MEM time output, so, I think native C code has already completed. 
The terminal output:**
[main] Version: 0.7.12-r1044
[main] CMD: bwa mem -t 16 /SHARE/zlq_workstation/bwa_test/hg19/gcat_01/hg19bwaidx file:/usr/local/hadoop/tmp/local-1466068623812-RDD0_1 file:/usr/local/hadoop/tmp/local-1466068623812-RDD0_2
[main] Real time: 446.167 sec; CPU: 7755.548 sec
[Java_BwaJni_bwa_1jni] Return code from BWA 0.
java.io.FileNotFoundException: File file:/usr/local/hadoop/tmp/SparkBWA_ERR000589_1.filt.fastq-1-NoSort-local-1466068623812-0.sam does not exist
    at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747)
    at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:524)
    at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
    at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:337)
    at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1905)
    at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1873)
    at org.apache.hadoop.fs.FileSystem.copyFromLocalFile(FileSystem.java:1838)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:344)
    at BwaRDD$BwaAlignment.call(BwaRDD.java:173)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.api.java.JavaRDDLike$$anonfun$mapPartitionsWithIndex$1.apply(JavaRDDLike.scala:105)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$22.apply(RDD.scala:745)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
16/06/16 17:27:13 ERROR BwaInterpreter: java.io.FileNotFoundException: File file:/usr/local/hadoop/tmp/SparkBWA_ERR000589_1.filt.fastq-1-NoSort-local-1466068623812-0.sam does not exist
16/06/16 17:27:13 INFO executor.Executor: Finished task 0.0 in stage 3.0 (TID 42). 1745 bytes result sent to driver
16/06/16 17:27:13 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 3.0 (TID 42) in 547608 ms on localhost (1/1)
16/06/16 17:27:13 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 3.0, whose tasks have all completed, from pool
16/06/16 17:27:13 INFO scheduler.DAGScheduler: ResultStage 3 (collect at BwaRDD.java:108) finished in 547.609 s
16/06/16 17:27:13 INFO scheduler.DAGScheduler: Job 0 finished: collect at BwaRDD.java:108, took 607.900833 s
16/06/16 17:27:13 INFO BwaInterpreter: BwaRDD :: Total of returned lines from RDDs :: 0
16/06/16 17:27:13 INFO spark.SparkContext: Invoking stop() from shutdown hook
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/api,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/static,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}

▽
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
16/06/16 17:27:13 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs,null}
16/06/16 17:27:13 INFO ui.SparkUI: Stopped Spark web UI at http://192.168.0.6:4040
16/06/16 17:27:13 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/06/16 17:27:14 INFO storage.MemoryStore: MemoryStore cleared
16/06/16 17:27:14 INFO storage.BlockManager: BlockManager stopped
16/06/16 17:27:14 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
16/06/16 17:27:14 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/06/16 17:27:14 INFO spark.SparkContext: Successfully stopped SparkContext
16/06/16 17:27:14 INFO util.ShutdownHookManager: Shutdown hook called
16/06/16 17:27:14 INFO util.ShutdownHookManager: Deleting directory /usr/local/spark/spark-a78bdd39-7734-46b4-ac65-5bc5e84020bf
16/06/16 17:27:14 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/06/16 17:27:14 INFO util.ShutdownHookManager: Deleting directory /usr/local/spark/spark-a78bdd39-7734-46b4-ac65-5bc5e84020bf/httpd-1d0d8654-4cfd-4430-8eb8-5445336a6bdc
16/06/16 17:27:14 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.

**Comment by jmabuin** [comment]
I think the error is in the arguments passed to bwa. If you take a look to the input fastq files, they start with **file:/**, but here we are talking about files in the local filesystem, so they don't have why to start with **file:/**. For example, here they should be _/usr/local/hadoop/_...

I always executed the tool using YARN, not in local mode, so maybe the error is caused by that. Let me do some findings and I will answer ASAP.

**Comment by jmabuin** [comment]
Can you please check if works after commit 9877d5a ?

**Comment by neozhang307** [comment]
Thanks, it works now. I will try using yarn later.

**Comment by jmabuin** [comment]
Ok, thanks to you for your feedback :)
