### ISSUE TITLE
mvn package compilation failing with certificate error

### ISSUE THREAD

**Issue by tushu1232** [citiususc/SparkBWA#40]
SparkBWA]$ ../apache-maven-3.3.9/bin/mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building SparkBWA 0.2
[INFO] ------------------------------------------------------------------------
Downloading: https://mvn.128.no/maven2/cz/adamh/utils/native-utils/1.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata cz.adamh.utils:native-utils:1.0-SNAPSHOT/maven-metadata.xml from/to 128 (https://mvn.128.no/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[WARNING] Failure to transfer cz.adamh.utils:native-utils:1.0-SNAPSHOT/maven-metadata.xml from https://mvn.128.no/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of 128 has elapsed or updates are forced. Original error: Could not transfer metadata cz.adamh.utils:native-utils:1.0-SNAPSHOT/maven-metadata.xml from/to 128 (https://mvn.128.no/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Downloading: https://mvn.128.no/maven2/cz/adamh/utils/native-utils/1.0-SNAPSHOT/native-utils-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.478 s
[INFO] Finished at: 2017-02-23T19:42:04+03:00
[INFO] Final Memory: 16M/568M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project SparkBWA: Could not resolve dependencies for project com.github.sparkbwa:SparkBWA:jar:0.2: Failed to collect dependencies at cz.adamh.utils:native-utils:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for cz.adamh.utils:native-utils:jar:1.0-SNAPSHOT: Could not transfer artifact cz.adamh.utils:native-utils:pom:1.0-SNAPSHOT from/to 128 (https://mvn.128.no/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tushu1232** [comment]
there was issue in my local repo

**Comment by tushu1232** [comment]
Reopening as after removing the .m2/ folder the error still was present
[Uploading mvnpackage.txt…]()

**Comment by tushu1232** [comment]
Reopening as after removing the .m2/ folder the error still was present
[mvnpackage.txt](https://github.com/citiususc/SparkBWA/files/797150/mvnpackage.txt)

**Comment by jmabuin** [comment]
https://github.com/citiususc/SparkBWA/issues/34

**Comment by tushu1232** [comment]
Closing this issue java 1.8.0_121 needed with maven 3.3.9 and it works
