### ISSUE TITLE
Unable to build with Maven

### ISSUE THREAD

**Issue by luederm** [citiususc/SparkBWA#41]
The 'mvn package' command gets hung when trying to download the spark-core dependency.

It prints out 'Downloading: https://mvn.128.no/maven2/org/apache/spark/spark-core_2.11/2.0.1/spark-core_2.11-2.0.1.pom' but never moves past this point.

I am using Linux and Maven version 3.3.9

**Comment by ghost** [comment]
Do you still have this issue? I just compiled with maven 3.5.0 and compiled fine after making sure my JAVA_HOME was pointing to the right place. On Linux.

**Comment by jmabuin** [comment]
https://github.com/citiususc/SparkBWA/issues/34
