### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by Nav15** [citiususc/SparkBWA#5]
Hi, 
I am using below command lien to run this application:
$SPARK_HOME/bin/spark-submit --class SparkBWA --master yarn-client  --driver-memory 1500m --executor-memory 1500m --executor-cores 1 --archives bwa.zip --verbose --num-executors 32 SparkBWA.jar -algorithm mem -reads paired -index /Data/HumanBase/ECOLI -partitions 32 ecoli_1.fq ecoli_2.fq Output_ECOLI

 We have 7 node cluster with 6core each node and 16GB . Input file size is hyst 5MB.

Exception stack trace:
**16/06/16 17:18:06 ERROR cluster.YarnScheduler: Lost executor 2 on client18.example.com: remote Akka client disassociated**
16/06/16 17:18:06 WARN remote.ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkExecutor@client18.example.com:58541] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
.
.
.
.
**org.apache.spark.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 0**

**Comment by neozhang307** [comment]
I met this problem "missing an output location for shuffle" before, and I solve it by allocating more resource to a single executor. 
maybe you can try 8G or more memory, more executor-cores like 6 cores, and reduce the number of num-executors.

**Comment by Nav15** [comment]
Hi,
 Tried  by increasing memory  ,used below command with 8GB memory for  driver and executor:
$SPARK_HOME/bin/spark-submit --class SparkBWA --master yarn-client **--driver-memory 8G** **--executor-memory 8G** **--executor-cores 6** --archives bwa.zip --verbose --num-executors 1 SparkBWA.jar -algorithm mem -reads paired -index /Data/HumanBase/ECOLI -partitions 32 /user/hadoop/ecoli_1.fq /user/hadoop/ecoli_2.fq Output_ECOLI

But still getting same error: Below is  my configuration:
1: Cluster enviorment setup: 7 Nodes , 6 cores per node ,12GB  Memory per node
2: Size of Reads and Index file is approx ~ 12+2=14MB (this is very small data set)

3: $SPARK_HOME/conf/spark-env.sh
SPARK_WORKER_INSTANCES=1
SPARK_WORKER_CORES=6
SPARK_EXECUTOR_MEMORY=12G
SPARK_DRIVER_MEMORY=4G
SPARK_WORKER_MEMORY=12G
4:  $SPARK_HOME/spark-defaults.conf
spark.executor.extraJavaOptions     -Djava.library.path=./bwa.zip
spark.yarn.executor.memoryOverhead   4000

5: yarn-site.xml
yarn.nodemanager.resource.memory-mb: 4000
yarn.scheduler.maximum-allocation-mb: 12000

**Error Stack trace on console:**
16/06/17 11:26:02 WARN scheduler.TaskSetManager: Lost task 6.0 in stage 2.4 (TID 75, client21.example.com): FetchFailed(null, shuffleId=0, mapId=-1, reduceId=6, message=
org.apache.spark.shuffle.MetadataFetchFailedException: Missing an output location for shuffle 0

**Logs snippet from yarn logs :**
16/06/17 11:25:13 INFO yarn.YarnAllocator: Will request 1 executor containers, each with 6 cores and 10240 MB memory including 2048 MB overhead
16/06/17 11:25:13 INFO yarn.YarnAllocator: Container request (host: Any, capability: <memory:10240, vCores:6>)
16/06/17 11:25:13 INFO yarn.ApplicationMaster: Started progress reporter thread - sleep time : 5000
16/06/17 11:25:18 INFO impl.AMRMClientImpl: Received new token for : client19.example.com:47667
16/06/17 11:25:18 INFO yarn.YarnAllocator: Launching container container_1466141495404_0002_02_000002 for on host client19.example.com
16/06/17 11:25:18 INFO yarn.YarnAllocator: Launching ExecutorRunnable. driverUrl: akka.tcp://sparkDriver@master.example.com:36817/user/CoarseGrainedSc
heduler,  executorHostname: client19.example.com
16/06/17 11:25:18 INFO yarn.YarnAllocator: Received 1 containers from YARN, launching executors on 1 of them.
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Starting Executor Container
16/06/17 11:25:18 INFO impl.ContainerManagementProtocolProxy: yarn.client.max-cached-nodemanagers-proxies : 0
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Setting up ContainerLaunchContext
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Preparing Local resources
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Prepared Local resources Map(**spark**.jar -> resource { scheme: "hdfs" host: "master" port: 9000 file: 
"/user/hadoop/.sparkStaging/application_1466141495404_0002/spark-assembly-1.3.1-hadoop2.6.0.jar" } size: 165034307 timestamp: 1466142836602 type: FILE
 visibility: PRIVATE, bwa.zip -> resource { scheme: "hdfs" host: "master" port: 9000 file: "/user/hadoop/.sparkStaging/application_1466141495404_0002/
bwa.zip" } size: 1001391 timestamp: 1466142836757 type: ARCHIVE visibility: PRIVATE)
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Setting up executor with environment: Map(CLASSPATH -> {{PWD}}<CPS>{{PWD}}/**spark**.jar<CPS>$HADOOP_CON
F_DIR<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/_<CPS>$HADOOP_COMMON_HOME/share/hadoop/common/lib/_<CPS>$HADOOP_HDFS_HOME/share/hadoop/hdfs/_<CPS>$H
ADOOP_HDFS_HOME/share/hadoop/hdfs/lib/_<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/_<CPS>$HADOOP_YARN_HOME/share/hadoop/yarn/lib/_<CPS>$HADOOP_MAPRED_HOM
E/share/hadoop/mapreduce/_<CPS>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/_, SPARK_YARN_CACHE_ARCHIVES -> hdfs://master:9000/user/hadoop/.sparkSta
ging/application_1466141495404_0002/bwa.zip#bwa.zip, SPARK_LOG_URL_STDERR -> http://client19.example.com:8042/node/containerlogs/container_14661414954
04_0002_02_000002/hadoop/stderr?start=0, SPARK_YARN_CACHE_FILES_FILE_SIZES -> 165034307, SPARK_YARN_STAGING_DIR -> .sparkStaging/application_146614149
5404_0002, SPARK_YARN_CACHE_FILES_VISIBILITIES -> PRIVATE, SPARK_YARN_CACHE_ARCHIVES_FILE_SIZES -> 1001391, SPARK_USER -> hadoop, SPARK_OPTS ->  -Djav
a.library.path=/opt/spark/spark-1.3.1-bin-hadoop2.6/lib, SPARK_YARN_CACHE_ARCHIVES_TIME_STAMPS -> 1466142836757, SPARK_YARN_MODE -> true, SPARK_HOME -> /opt/spark/spark-1.3.1-bin-hadoop2.6, SPARK_YARN_CACHE_FILES_TIME_STAMPS -> 1466142836602, SPARK_LOG_URL_STDOUT -> http://client19.example.com:8042/node/containerlogs/container_1466141495404_0002_02_000002/hadoop/stdout?start=0, SPARK_YARN_CACHE_ARCHIVES_VISIBILITIES -> PRIVATE, SPARK_YARN_CACHE_FILES -> hdfs://master:9000/user/hadoop/.sparkStaging/application_1466141495404_0002/spark-assembly-1.3.1-hadoop2.6.0.jar#**spark**.jar)
16/06/17 11:25:18 INFO yarn.ExecutorRunnable: Setting up executor with commands: List({{JAVA_HOME}}/bin/java, -server, -XX:OnOutOfMemoryError='kill %p', -Xms8192m, -Xmx8192m, '-Djava.library.path=./bwa.zip', -Djava.io.tmpdir={{PWD}}/tmp, '-Dspark.driver.port=36817', -Dspark.yarn.app.container.log.dir=<LOG_DIR>, org.apache.spark.executor.CoarseGrainedExecutorBackend, --driver-url, akka.tcp://sparkDriver@master.example.com:36817/user/CoarseGrainedScheduler, --executor-id, 1, --hostname, client19.example.com, --cores, 6, --app-id, application_1466141495404_0002, --user-class-path, file:$PWD/**app**.jar, 1>, <LOG_DIR>/stdout, 2>, <LOG_DIR>/stderr)
16/06/17 11:25:18 INFO impl.ContainerManagementProtocolProxy: Opening proxy : client19.example.com:47667
16/06/17 11:25:28 INFO yarn.YarnAllocator: Completed container container_1466141495404_0002_02_000002 (state: COMPLETE, exit status: 1)
16/06/17 11:25:28 INFO yarn.YarnAllocator: Container marked as failed: container_1466141495404_0002_02_000002. Exit status: 1. Diagnostics: Exception from container-launch.
Container id: container_1466141495404_0002_02_000002
Exit code: 1
Stack trace: ExitCodeException exitCode=1: 
        at org.apache.hadoop.util.Shell.runCommand(Shell.java:538)
        at org.apache.hadoop.util.Shell.run(Shell.java:455)
        at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:715)
        at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:211)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
        at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Container exited with a non-zero exit code 1

**Comment by Nav15** [comment]
Also  can you  please share the  command to run this application using spark-shell?

**Comment by neozhang307** [comment]
spark-submit --class SparkBWA --master local[16] --driver-memory 15G --executor-memory 15G --executor-cores 16 --archives ./bwa.zip --verbose --num-executors 1  SparkBWA.jar  -algorithm mem -reads paired -partitions 1 -index /SHARE/zlq_workstation/bwa_test/hg19/gcat_01/hg19bwaidx -threads 16 /user/zlq/input/ERR000589_1.filt.fastq /user/zlq/input/ERR000589_2.filt.fastq /user/zlq/ERR00589_out

**Comment by Nav15** [comment]
Thanks ran this and   got something like this:
16/06/17 13:06:48 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-13,5,main]
java.lang.UnsatisfiedLinkError: no bwa in java.library.path

 Though defined same  in:
conf/spark-defaults.conf
**spark.executor.extraJavaOptions     -Djava.library.path=./bwa.zip**

Also ,How can i fire this job using  spark-shell instead of spark-submit?

**Comment by neozhang307** [comment]
Sorry, but I can't ...

**Comment by jmabuin** [comment]
@Nav15 please, check https://github.com/citiususc/SparkBWA/issues/6 to see if you are having the problem.

**Comment by Nav15** [comment]
@jmabuin , That is  different issue.
 I can see that build directory contains SparkBWA.jar,bwa.zip and many others files.  And I am  submitting the application from /build directory. That is different issue reported. Mine is:
**16/06/16 17:18:06 ERROR cluster.YarnScheduler: Lost executor 2 on client18.example.com: remote Akka client disassociated**

**Comment by jmabuin** [comment]
Generally, this kind of errors are because of the lack of disk space or RAM memory. Also, I the size in **spark.yarn.executor.memoryOverhead 4000** can be very low.
In our tests using GRCH38 as index it needs to be 6-7GB

**Comment by Nav15** [comment]
I am using the ECOLI data set for which  Read+Input data size= 7MB.

**Comment by jmabuin** [comment]
Can you try to decrease the number of executors to, for example, 8 ?

**Comment by Nav15** [comment]
checked with 1,2,...8 . But  error is same

**Comment by Nav15** [comment]
Please close.
