### ISSUE TITLE
Output is empty .sam file!!

### ISSUE THREAD

**Issue by Rokshan2016** [citiususc/SparkBWA#51]
Hi,
I am using this command -

/opt/cloudera/parcels/CDH-5.10.1-1.cdh5.10.1.p0.10/lib/spark/bin/spark-submit --class com.github.sparkbwa.SparkBWA --master yarn-cluster --driver-memory 10g --executor-memory 10g --executor-cores 1 --verbose --num-executors 32 /home/rokshan.jahan/adamproject/SparkBWA-master/target/SparkBWA-0.2.jar -m -r -s --index /home/rokshan.jahan/adamproject/reference/ref/Homo_sapiens_assembly.fasta -w   "-R @RG\tID:SRR1517974\tLB:SRR1517974\tPL:illumina\tPU:illumina\tSM:SRR1517974" hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/fastqdata/SRR1517974.fastq hdfs://ip-10-48-3-5.ips.local:8020/user/rokshan.jahan/data/SRR1517974.sam

Index file I am using :  
Homo_sapiens_assembly.fasta.sa
Homo_sapiens_assembly.fasta.pac
Homo_sapiens_assembly.fasta.fai
Homo_sapiens_assembly.fasta.bwt
Homo_sapiens_assembly.fasta.ann
Homo_sapiens_assembly.fasta.amb
      

I am not getting any error, but output is getting  empty sam file-- SRR1517974.sam

Looks like its not reading the index files. How should I give the path, so that it can read the index file? 

Can anyone please help me with this. Any suggestion will be really helpful!

Thanks

**Comment by Maryom** [comment]
Hey @Rokshan2016 ,

Did you find a solution? I have the same issue
