### ISSUE TITLE
Missing an output location for shuffle 0

### ISSUE THREAD

**Issue by Shenglai** [citiususc/SparkBWA#53]
hi all.
i’m still struggling with the sparkbwa. 
For some background, i was trying to run the sparkbwa on my standalone spark cluster (1master + 1worker in one node with a flavor of ram200.disk10.eph1500.core40). however, right now it had been stuck at one stage:
```
collect at BwaInterpreter.java:305
org.apache.spark.api.java.AbstractJavaRDDLike.collect(JavaRDDLike.scala:45)
com.github.sparkbwa.BwaInterpreter.MapPairedBwa(BwaInterpreter.java:305)
com.github.sparkbwa.BwaInterpreter.runBwa(BwaInterpreter.java:334)
com.github.sparkbwa.SparkBWA.main(SparkBWA.java:37)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
in this stage, it would take all the memory in the node no matter how much memory i pre-set in the command or spark-env.sh, and error out `Missing an output location for shuffle 0` after ~10-20 min. the command i’m using is
```
spark-submit --deploy-mode client --driver-memory 50g --master spark://bioinfo-uni
corns-slurm-claire-worker-40:7077 --total-executor-cores 40 --executor-memory 10g --class com.github.sparkbwa.SparkBWA --verbose SparkBWA-0.2.jar -n 40 -m -r -p --index /mnt/refe
rence/GRCh38.d1.vd1.fa -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" /user/ERR000589_1.filt.fastq /user/ERR000589_2.filt.fastq /user/Output_ERR000589
```
for `driver-memory`, i have to set it over 2G otherwise it would fail to java out of heap due to the fact that i’m running in standalone mode, which spark driver runs with spark client. (i'm not very confident about my understanding since i'm new to the spark.) the reason i increased it to 50G is because the application is failing at `.collect` stage, and from google search i got this:  
>Operations like .collect,.take and takeSample deliver data to the driver and hence, the driver needs enough memory to allocate such data. 

https://stackoverflow.com/questions/27181737/how-to-deal-with-executor-memory-and-driver-memory-in-spark

for `executor-memory`, no matter how much i set, it would always take all the memory in the node at `.collect` stage as i mentioned.

i have tried different memory settings for both driver and executor memory, but no combination of the settings worked so far. (driver small value of memory and executor big, reversed, both small, both big, nothing works)

i also tried adding `spark.shuffle.memoryFraction 0` in spark-default.conf, but it's not helping as well. 

Please find the attachment which is the screen shot from the spark ui
![screen shot 2017-11-30 at 1 48 32 pm](https://user-images.githubusercontent.com/8419787/33451722-8478c166-d5d5-11e7-8e10-ed09efe4fd69.png)

i also attached the screen shot before `.collect` failed, which you could see it used all the memory.
![screen shot 2017-11-30 at 1 56 00 pm](https://user-images.githubusercontent.com/8419787/33452005-5bd30e14-d5d6-11e7-9d9a-da9c1b03c59c.png)

i know it's kind of a spark question, and really sorry that i am unable to figure it out myself. however, i’m just wondering if you have some experience or have any insights of my situation. ty so much in advance.

Edit:

i also attached log files from spark master and worker. All the screen shots and logs are from the same single run, with the command:
```
/usr/bin/time -v spark-submit \
--deploy-mode client --driver-memory 2g --master spark://bioinfo-unicorns-slurm-claire-worker-40:7077 \
--total-executor-cores 32 --executor-memory 10g \
--class com.github.sparkbwa.SparkBWA \
--verbose SparkBWA-0.2.jar -n 32 -m -r -p --index /mnt/reference/GRCh38.d1.vd1.fa -w "-R @RG\tID:foo\tLB:bar\tPL:illumina\tPU:illumina\tSM:ERR000589" /user/ERR000589_1.filt.fastq /user/ERR000589_2.filt.fastq /user/Output_ERR000589
```
[master_log.txt](https://github.com/citiususc/SparkBWA/files/1519311/master_log.txt)
[worker_log.txt](https://github.com/citiususc/SparkBWA/files/1519313/worker_log.txt)

**Comment by Dineshvrma** [comment]
Hi Shenglai, Could you please help me what has solved the above error, I am facing the same..My mail id is : dinesh.ecbe@gmail.com
