### ISSUE TITLE
run with single-end error

### ISSUE THREAD

**Issue by xubo245** [citiususc/SparkBWA#7]
shell:

```
spark-submit --class SparkBWA \
--master yarn-client \
--archives bwa.zip \
--verbose \
SparkBWA.jar \
-algorithm mem -reads single \
-index /home/hadoop/xubo/ref/GRCH38L1Index/GRCH38chr1L3556522.fasta \
-sorting hdfs \
-partitions 3 \
/xubo/alignment/sparkBWA/GRCH38chr1L3556522N10000SE.fastq \
/xubo/alignment/output/sparkBWA/datatest11se
```

error:

```
hadoop@Master:~/xubo/project/alignment/sparkBWA$ ./seGRCH38L1.sh 
Using properties file: /home/hadoop/cloud/spark-1.5.2/conf/spark-defaults.conf
Adding default property: spark.executor.extraJavaOptions=-Djava.library.path=/home/hadoop/xubo/tools/SparkBWA/build/bwa.zip
Adding default property: spark.eventLog.enabled=true
Adding default property: spark.eventLog.dir=file:///home/hadoop/Downloads/hangc/sparklog
Adding default property: spark.eventLog.compress=true
Adding default property: spark.yarn.executor.memoryOverhead=3704
Parsed arguments:
  master                  yarn-client
  deployMode              null
  executorMemory          4G
  executorCores           null
  totalExecutorCores      null
  propertiesFile          /home/hadoop/cloud/spark-1.5.2/conf/spark-defaults.conf
  driverMemory            2G
  driverCores             null
  driverExtraClassPath    null
  driverExtraLibraryPath  null
  driverExtraJavaOptions  null
  supervise               false
  queue                   null
  numExecutors            null
  files                   null
  pyFiles                 null
  archives                file:/home/hadoop/xubo/project/alignment/sparkBWA/bwa.zip
  mainClass               SparkBWA
  primaryResource         file:/home/hadoop/xubo/project/alignment/sparkBWA/SparkBWA.jar
  name                    SparkBWA
  childArgs               [-algorithm mem -reads single -index /home/hadoop/xubo/ref/GRCH38L1Index/GRCH38chr1L3556522.fasta -sorting hdfs -partitions 3 /xubo/alignment/sparkBWA/GRCH38chr1L3556522N10000SE.fastq /xubo/alignment/output/sparkBWA/datatest11se]
  jars                    null
  packages                null
  packagesExclusions      null
  repositories            null
  verbose                 true

Spark properties used, including those specified through
 --conf and those from the properties file /home/hadoop/cloud/spark-1.5.2/conf/spark-defaults.conf:
  spark.eventLog.enabled -> true
  spark.eventLog.compress -> true
  spark.executor.extraJavaOptions -> -Djava.library.path=/home/hadoop/xubo/tools/SparkBWA/build/bwa.zip
  spark.yarn.executor.memoryOverhead -> 3704
  spark.eventLog.dir -> file:///home/hadoop/Downloads/hangc/sparklog


Main class:
SparkBWA
Arguments:
-algorithm
mem
-reads
single
-index
/home/hadoop/xubo/ref/GRCH38L1Index/GRCH38chr1L3556522.fasta
-sorting
hdfs
-partitions
3
/xubo/alignment/sparkBWA/GRCH38chr1L3556522N10000SE.fastq
/xubo/alignment/output/sparkBWA/datatest11se
System properties:
spark.driver.memory -> 2G
spark.executor.memory -> 4G
spark.eventLog.enabled -> true
spark.eventLog.compress -> true
SPARK_SUBMIT -> true
spark.executor.extraJavaOptions -> -Djava.library.path=/home/hadoop/xubo/tools/SparkBWA/build/bwa.zip
spark.app.name -> SparkBWA
spark.yarn.executor.memoryOverhead -> 3704
spark.jars -> file:/home/hadoop/xubo/project/alignment/sparkBWA/SparkBWA.jar
spark.submit.deployMode -> client
spark.yarn.dist.archives -> file:/home/hadoop/xubo/project/alignment/sparkBWA/bwa.zip
spark.eventLog.dir -> file:///home/hadoop/Downloads/hangc/sparklog
spark.master -> yarn-client
Classpath elements:
file:/home/hadoop/xubo/project/alignment/sparkBWA/SparkBWA.jar


Exception in thread "main" java.lang.IllegalArgumentException: Can not create a Path from an empty string
    at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
    at org.apache.hadoop.fs.Path.<init>(Path.java:135)
    at BwaInterpreter.SortInHDFS2(BwaInterpreter.java:499)
    at BwaInterpreter.initInterpreter(BwaInterpreter.java:405)
    at BwaInterpreter.<init>(BwaInterpreter.java:94)
    at SparkBWA.main(SparkBWA.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:674)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

sorting with spark error:
`datasetTmp2 = ctx.newAPIHadoopFile(options.getInputPath2(), FastqInputFormat.class, Long.class, String.class,this.conf).persist(StorageLevel.MEMORY_ONLY());
`

sorting with hdfs error:

`pairedDataRDD = this.SortInHDFS2(options.getInputPath(), options.getInputPath2());//.persist(StorageLevel.MEMORY_ONLY());`

the code in BwaOptions:

```
    else if(otherArguments.length == 2){
                inputPath = otherArguments[0];
                outputPath = otherArguments[1];
            }
            else if (otherArguments.length == 3){
                inputPath = otherArguments[0];
                inputPath2 = otherArguments[1];
                outputPath = otherArguments[2];
            }
```

It should be support single,but why do not support in  public void initInterpreter() ?

**Comment by Nav15** [comment]
@xubo245, 
 I will try to reproduce this at my end, and will update  you.
 Did you manage to get rid of earlier issue :" Cannot satrt SparkBWA #6 "

If possible can you share your bashrc file and spark.defaults.conf, sparl.env.sh file?
 If Yes, could you please  advise me too.

**Comment by xubo245** [comment]
@Nav15  No ,I am looking for source code in SparkBWA ，I have not found the reason......

I will check the .so file later，Now the problem is “Caused by: java.lang.NoClassDefFoundError: Could not initialize class BwaJni”。

there are another similar project ，you can try：https://github.com/ytchen0323/cloud-scale-bwamem

**Comment by jmabuin** [comment]
The single reads algorithm is not yet in the repository, I will try to upload it next week

**Comment by xubo245** [comment]
@jmabuin Thank you.

**Comment by jmabuin** [comment]
In  891d542 I just merged pull request that include the single reads algorithm from @paalka

**Comment by avapirev** [comment]
I hit the same error "Can not create a Path from an empty string " every time I try single-end reads. No matter if I use Spark standalone, or with Yarn. I have check the data and disk integrity - no problems there. Here is the full log from the error 

`17/08/01 12:45:28 INFO scheduler.DAGScheduler: ResultStage 0 (zipWithIndex at BwaInterpreter.java:152) finished in 281.332 s
17/08/01 12:45:28 INFO cluster.YarnClusterScheduler: Removed TaskSet 0.0, whose tasks have all completed, from pool 
17/08/01 12:45:28 INFO scheduler.DAGScheduler: Job 0 finished: zipWithIndex at BwaInterpreter.java:152, took 281.489673 s
17/08/01 12:45:28 INFO storage.MemoryStore: ensureFreeSpace(302416) called with curMem=327400, maxMem=20615905935
17/08/01 12:45:28 INFO storage.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 295.3 KB, free 19.2 GB)
17/08/01 12:45:28 INFO storage.MemoryStore: ensureFreeSpace(20252) called with curMem=629816, maxMem=20615905935
17/08/01 12:45:28 INFO storage.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 19.8 KB, free 19.2 GB)
17/08/01 12:45:28 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on 172.23.9.74:34877 (size: 19.8 KB, free: 19.2 GB)
17/08/01 12:45:28 INFO spark.SparkContext: Created broadcast 2 from textFile at BwaInterpreter.java:149
17/08/01 12:45:28 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: Can not create a Path from an empty string
java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
	at org.apache.hadoop.fs.Path.<init>(Path.java:135)
	at org.apache.hadoop.util.StringUtils.stringToPath(StringUtils.java:244)
	at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:409)
	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$32.apply(SparkContext.scala:1016)
	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$32.apply(SparkContext.scala:1016)
	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:176)
	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:176)
	at scala.Option.map(Option.scala:145)
	at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:176)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:200)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.ZippedWithIndexRDD.<init>(ZippedWithIndexRDD.scala:44)
	at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1246)
	at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1246)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.zipWithIndex(RDD.scala:1245)
	at org.apache.spark.api.java.JavaRDDLike$class.zipWithIndex(JavaRDDLike.scala:321)
	at org.apache.spark.api.java.AbstractJavaRDDLike.zipWithIndex(JavaRDDLike.scala:47)
	at com.github.sparkbwa.BwaInterpreter.loadFastq(BwaInterpreter.java:152)
	at com.github.sparkbwa.BwaInterpreter.handlePairedReadsSorting(BwaInterpreter.java:239)
	at com.github.sparkbwa.BwaInterpreter.runBwa(BwaInterpreter.java:333)
	at com.github.sparkbwa.SparkBWA.main(SparkBWA.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:525)
17/08/01 12:45:28 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.IllegalArgumentException: Can not create a Path from an empty string)
17/08/01 12:45:28 INFO spark.SparkContext: Invoking stop() from shutdown hook
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/api,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/static,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/executors,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/environment,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/storage,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/stages,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
17/08/01 12:45:28 INFO handler.ContextHandler: stopped o.s.j.s.ServletContextHandler{/jobs,null}
17/08/01 12:45:28 INFO ui.SparkUI: Stopped Spark web UI at http://172.23.9.74:41490
17/08/01 12:45:28 INFO scheduler.DAGScheduler: Stopping DAGScheduler
17/08/01 12:45:28 INFO cluster.YarnClusterSchedulerBackend: Shutting down all executors
17/08/01 12:45:28 INFO cluster.YarnClusterSchedulerBackend: Asking each executor to shut down
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n6.thinking.leuven.vsc:34925
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n14.thinking.leuven.vsc:43852
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n2.thinking.leuven.vsc:45454
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n8.thinking.leuven.vsc:38231
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r3i0n15.thinking.leuven.vsc:44938
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n9.thinking.leuven.vsc:46302
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n4.thinking.leuven.vsc:44478
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n11.thinking.leuven.vsc:35098
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n14.thinking.leuven.vsc:37700
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n4.thinking.leuven.vsc:35676
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n6.thinking.leuven.vsc:37204
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r3i0n14.thinking.leuven.vsc:34888
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n11.thinking.leuven.vsc:44106
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r3i0n14.thinking.leuven.vsc:43985
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n3.thinking.leuven.vsc:46533
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r3i0n15.thinking.leuven.vsc:39727
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n9.thinking.leuven.vsc:33322
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n5.thinking.leuven.vsc:45842
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n15.thinking.leuven.vsc:37554
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n3.thinking.leuven.vsc:42387
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n4.thinking.leuven.vsc:43140
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n12.thinking.leuven.vsc:33092
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n5.thinking.leuven.vsc:37231
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n10.thinking.leuven.vsc:41635
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n3.thinking.leuven.vsc:35557
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n10.thinking.leuven.vsc:34186
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i2n10.thinking.leuven.vsc:34124
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n2.thinking.leuven.vsc:38892
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n5.thinking.leuven.vsc:44296
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n5.thinking.leuven.vsc:39207
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n13.thinking.leuven.vsc:38967
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n13.thinking.leuven.vsc:35399
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n15.thinking.leuven.vsc:32933
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i2n10.thinking.leuven.vsc:44822
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n2.thinking.leuven.vsc:42594
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n3.thinking.leuven.vsc:34750
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n12.thinking.leuven.vsc:33609
17/08/01 12:45:28 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n4.thinking.leuven.vsc:43560
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r4i0n2.thinking.leuven.vsc:43352
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n1.thinking.leuven.vsc:37295
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n1.thinking.leuven.vsc:42513
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n8.thinking.leuven.vsc:35885
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r1i1n6.thinking.leuven.vsc:40815
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i2n11.thinking.leuven.vsc:36843
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i2n11.thinking.leuven.vsc:36079
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n16.thinking.leuven.vsc:34914
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n16.thinking.leuven.vsc:37117
17/08/01 12:45:29 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r1i1n6.thinking.leuven.vsc:38277
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n7.thinking.leuven.vsc:39113
17/08/01 12:45:29 INFO yarn.ApplicationMaster$AMEndpoint: Driver terminated or disconnected! Shutting down. r2i0n7.thinking.leuven.vsc:34719
17/08/01 12:45:29 INFO storage.MemoryStore: MemoryStore cleared
17/08/01 12:45:29 INFO storage.BlockManager: BlockManager stopped
17/08/01 12:45:29 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
17/08/01 12:45:29 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
17/08/01 12:45:29 INFO spark.SparkContext: Successfully stopped SparkContext
17/08/01 12:45:29 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.IllegalArgumentException: Can not create a Path from an empty string)
17/08/01 12:45:29 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
17/08/01 12:45:29 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
17/08/01 12:45:29 INFO impl.AMRMClientImpl: Waiting for application to be successfully unregistered.
17/08/01 12:45:29 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
17/08/01 12:45:29 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1501582874205_0002
17/08/01 12:45:29 ERROR yarn.ApplicationMaster: Failed to cleanup staging dir .sparkStaging/application_1501582874205_0002
java.io.IOException: Filesystem closed
	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:795)
	at org.apache.hadoop.hdfs.DFSClient.delete(DFSClient.java:1927)
	at org.apache.hadoop.hdfs.DistributedFileSystem$12.doCall(DistributedFileSystem.java:638)
	at org.apache.hadoop.hdfs.DistributedFileSystem$12.doCall(DistributedFileSystem.java:634)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:634)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$cleanupStagingDir(ApplicationMaster.scala:413)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:135)
	at org.apache.spark.util.SparkShutdownHook.run(ShutdownHookManager.scala:264)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ShutdownHookManager.scala:234)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:234)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1$$anonfun$apply$mcV$sp$1.apply(ShutdownHookManager.scala:234)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1699)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply$mcV$sp(ShutdownHookManager.scala:234)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:234)
	at org.apache.spark.util.SparkShutdownHookManager$$anonfun$runAll$1.apply(ShutdownHookManager.scala:234)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.util.SparkShutdownHookManager.runAll(ShutdownHookManager.scala:234)
	at org.apache.spark.util.SparkShutdownHookManager$$anon$2.run(ShutdownHookManager.scala:216)
	at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)
17/08/01 12:45:29 INFO util.ShutdownHookManager: Shutdown hook called
17/08/01 12:45:29 INFO util.ShutdownHookManager: Deleting directory /ddn1/vol1/site_scratch/leuven/304/vsc30484/mapred_scratch/usercache/vsc30484/appcache/application_1501582874205_0002/spark-6a89e3e0-6f21-404d-92d4-53617616daa3`
